machine:
    java:
        version: openjdk8

        version: 2
jobs:
  build:
    
    steps:

      - checkout

      - restore_cache:
          key: nl.dotWebly-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: nl.dotWebly-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      